const tools=[
{id:'rotary-hammer',name:'Перфоратор SDS+',cat:'power',icon:'🔨',price:3500,deposit:25000,power:900,pop:96,desc:'Для бурения бетона, кирпича и демонтажа.',spec:['900 Вт','SDS+','3 режима']},
{id:'impact-driver',name:'Шуруповёрт ударный',cat:'power',icon:'🪛',price:2200,deposit:18000,power:350,pop:92,desc:'Монтаж, каркас, мебель и крепёж.',spec:['18V','2 АКБ','кейс']},
{id:'laser-level',name:'Лазерный уровень 360°',cat:'measure',icon:'📐',price:2800,deposit:22000,power:35,pop:88,desc:'Разметка плитки, потолков, перегородок.',spec:['зелёный луч','штатив','±0.2мм']},
{id:'concrete-mixer',name:'Бетономешалка 180 л',cat:'heavy',icon:'🧱',price:6500,deposit:55000,power:850,pop:80,desc:'Для раствора и бетона на объекте.',spec:['180 л','колёса','850 Вт']},
{id:'tile-cutter',name:'Плиткорез электрический',cat:'power',icon:'🧩',price:4200,deposit:30000,power:1200,pop:76,desc:'Аккуратный рез керамики и керамогранита.',spec:['водяное охл.','1200 Вт','45°']},
{id:'compactor',name:'Виброплита',cat:'heavy',icon:'🚧',price:12000,deposit:120000,power:4200,pop:67,desc:'Уплотнение песка, щебня и тротуарной плитки.',spec:['90 кг','бензин','20 кН']},
{id:'generator',name:'Генератор 3 кВт',cat:'heavy',icon:'⚡',price:9000,deposit:90000,power:0,pop:73,desc:'Автономное питание инструмента на объекте.',spec:['3 кВт','бензин','AVR']},
{id:'grinder',name:'Болгарка 230 мм',cat:'power',icon:'⚙️',price:2500,deposit:20000,power:2200,pop:91,desc:'Рез металла, камня и зачистка поверхностей.',spec:['230 мм','2200 Вт','плавный пуск']},
{id:'pressure-washer',name:'Мойка высокого давления',cat:'garden',icon:'💦',price:5000,deposit:42000,power:2000,pop:70,desc:'Очистка фасадов, плитки, техники и двора.',spec:['160 бар','2000 Вт','шланг 8м']},
{id:'scaffold',name:'Вышка-тура',cat:'heavy',icon:'🏗️',price:7500,deposit:65000,power:0,pop:62,desc:'Безопасная работа на высоте до 5 метров.',spec:['5 м','платформа','колёса']},
{id:'chainsaw',name:'Цепная пила',cat:'garden',icon:'🪚',price:4600,deposit:38000,power:1800,pop:69,desc:'Распил древесины, демонтаж и садовые работы.',spec:['40 см','1800 Вт','масло']},
{id:'thermal-camera',name:'Тепловизор',cat:'measure',icon:'🌡️',price:8000,deposit:95000,power:25,pop:58,desc:'Поиск теплопотерь, проводки и влажных зон.',spec:['IR','отчёт','USB-C']}
];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))},del(k){localStorage.removeItem(k)}};
const state={order:store.get('toolrent-order',tools.map(t=>t.id)),selected:store.get('toolrent-selected',[]),query:'',cat:'all',sort:'popular',days:store.get('toolrent-days',3),delivery:store.get('toolrent-delivery',0),client:store.get('toolrent-client',1)};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>Math.round(n).toLocaleString('ru-RU')+' ₸';
const throttle=(fn,wait=80)=>{let t=0;return(...a)=>{const n=Date.now();if(n-t>wait){t=n;fn(...a)}}};
const debounce=(fn,wait=180)=>{let id;return(...a)=>{clearTimeout(id);id=setTimeout(()=>fn(...a),wait)}};
function escapeReg(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function highlight(text,q){if(!q)return text;return text.replace(new RegExp('('+escapeReg(q)+')','ig'),'<mark>$1</mark>')}
function orderedTools(){const map=new Map(tools.map(t=>[t.id,t]));let list=state.order.map(id=>map.get(id)).filter(Boolean); tools.forEach(t=>{if(!state.order.includes(t.id))list.push(t)}); if(state.cat!=='all')list=list.filter(t=>t.cat===state.cat); if(state.query){const q=state.query.toLowerCase();list=list.filter(t=>(t.name+t.desc+t.spec.join(' ')).toLowerCase().includes(q));} if(state.sort==='priceAsc')list.sort((a,b)=>a.price-b.price); if(state.sort==='priceDesc')list.sort((a,b)=>b.price-a.price); if(state.sort==='depositAsc')list.sort((a,b)=>a.deposit-b.deposit); if(state.sort==='popular')list.sort((a,b)=>b.pop-a.pop); return list}
function renderCatalog(){const grid=$('#catalogGrid');grid.innerHTML='';const frag=document.createDocumentFragment();orderedTools().forEach((t,i)=>{const card=document.createElement('article');card.className='tool-card '+(state.selected.includes(t.id)?'selected':'');card.draggable=true;card.dataset.id=t.id;card.style.animationDelay=(i*35)+'ms';card.innerHTML=`<div class="tool-card__image"><span class="badge">${catName(t.cat)} · ${t.pop}%</span><span class="tool-icon" aria-hidden="true">${t.icon}</span></div><div class="tool-card__body"><h3>${highlight(t.name,state.query)}</h3><p>${highlight(t.desc,state.query)}</p><div class="specs">${t.spec.map(s=>`<span>${highlight(s,state.query)}</span>`).join('')}</div><div class="price-line"><span>сутки</span><b>${money(t.price)}</b></div><div class="price-line"><span>залог</span><strong>${money(t.deposit)}</strong></div><button class="btn btn--soft select-btn" type="button" aria-pressed="${state.selected.includes(t.id)}">${state.selected.includes(t.id)?'Убрать из заказа':'Добавить в заказ'}</button></div>`;card.querySelector('button').addEventListener('click',()=>toggleTool(t.id));frag.appendChild(card)});grid.appendChild(frag);bindDrag();renderTotals()}
function catName(c){return {power:'Электро',measure:'Измерение',heavy:'Техника',garden:'Сад'}[c]||c}
function toggleTool(id){state.selected=state.selected.includes(id)?state.selected.filter(x=>x!==id):[...state.selected,id];store.set('toolrent-selected',state.selected);renderCatalog()}
function renderTotals(){const selected=tools.filter(t=>state.selected.includes(t.id));const rent=selected.reduce((s,t)=>s+t.price,0)*Number(state.days)*Number(state.client);const deposit=selected.reduce((s,t)=>s+t.deposit,0);const delivery=Number(state.delivery);const grand=rent+delivery;$('#rentTotal').textContent=money(rent);$('#depositTotal').textContent=money(deposit);$('#deliveryTotal').textContent=money(delivery);$('#grandTotal').textContent=money(grand);$('#liveTotal').textContent=money(grand);const list=$('#cartList');list.innerHTML=selected.length?selected.map(t=>`<div class="cart-item"><span>${t.icon} ${t.name}</span><b>${money(t.price*state.days)}</b></div>`).join(''):'<p class="muted">Пока ничего не выбрано.</p>';renderChecklist(selected,rent,deposit,delivery);drawChart(selected)}
function renderChecklist(selected,rent,deposit,delivery){const power=selected.reduce((s,t)=>s+t.power,0);const heavy=selected.filter(t=>t.cat==='heavy').length;const items=[selected.length?`✅ Выбрано позиций: ${selected.length}`:'⚠️ Добавьте хотя бы один инструмент',power>3500?'⚠️ Высокая нагрузка: лучше взять генератор/отдельную линию':`✅ Нагрузка в норме: ${power} Вт`,heavy&&delivery===0?'⚠️ Для тяжёлого оборудования рекомендуется доставка':'✅ Логистика выглядит нормально',rent>0?`✅ Расчёт аренды готов: ${money(rent)}`:'⚠️ Цена появится после выбора'];$('#checklist').innerHTML=items.map(x=>`<li>${x}</li>`).join('')}
function drawChart(selected){const c=$('#categoryChart');if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);const cats=['power','measure','heavy','garden'];const counts=cats.map(cat=>selected.filter(t=>t.cat===cat).length || tools.filter(t=>t.cat===cat).length/3);const max=Math.max(...counts,1);ctx.font='16px Segoe UI';ctx.lineWidth=1;cats.forEach((cat,i)=>{const h=counts[i]/max*170;const x=45+i*110;const y=220-h;const grad=ctx.createLinearGradient(0,y,0,220);grad.addColorStop(0,'#ffb000');grad.addColorStop(1,'#ff6a00');ctx.fillStyle=grad;roundRect(ctx,x,y,64,h,14);ctx.fill();ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');ctx.fillText(catName(cat),x-6,245)})}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function bindDrag(){let dragged=null;$$('.tool-card').forEach(card=>{card.addEventListener('dragstart',e=>{dragged=card;card.classList.add('dragging');e.dataTransfer.effectAllowed='move'});card.addEventListener('dragend',()=>{card.classList.remove('dragging');dragged=null;state.order=$$('.tool-card').map(x=>x.dataset.id);store.set('toolrent-order',state.order)});card.addEventListener('dragover',throttle(e=>{e.preventDefault();const grid=$('#catalogGrid');const after=getAfterElement(grid,e.clientY,e.clientX);if(after==null)grid.appendChild(dragged);else grid.insertBefore(dragged,after)},50));})}
function getAfterElement(container,y,x){const els=[...container.querySelectorAll('.tool-card:not(.dragging)')];return els.reduce((closest,child)=>{const box=child.getBoundingClientRect();const offset=y-box.top-box.height/2 + (x-box.left-box.width/2)*0.15; if(offset<0&&offset>closest.offset)return{offset,element:child}; return closest},{offset:Number.NEGATIVE_INFINITY}).element}
function init(){setTimeout(()=>$('#loader').classList.add('hidden'),450);$('#searchInput').addEventListener('input',debounce(e=>{state.query=e.target.value.trim();renderCatalog()},170));$('#categoryFilter').addEventListener('change',e=>{state.cat=e.target.value;renderCatalog()});$('#sortFilter').addEventListener('change',e=>{state.sort=e.target.value;renderCatalog()});$('#daysInput').value=state.days;$('#deliverySelect').value=state.delivery;$('#clientSelect').value=state.client;['daysInput','deliverySelect','clientSelect'].forEach(id=>$('#'+id).addEventListener('input',()=>{state.days=Math.max(1,Number($('#daysInput').value||1));state.delivery=Number($('#deliverySelect').value);state.client=Number($('#clientSelect').value);store.set('toolrent-days',state.days);store.set('toolrent-delivery',state.delivery);store.set('toolrent-client',state.client);renderTotals()}));$('#themeBtn').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('toolrent-theme',next);$('#themeBtn').textContent=next==='dark'?'☀':'🌙';drawChart(tools.filter(t=>state.selected.includes(t.id)))});$('#themeBtn').textContent=document.documentElement.dataset.theme==='dark'?'☀':'🌙';$('#resetBtn').addEventListener('click',()=>{['toolrent-order','toolrent-selected','toolrent-days','toolrent-delivery','toolrent-client','toolrent-theme'].forEach(k=>localStorage.removeItem(k));location.reload()});$('#exportBtn').addEventListener('click',()=>{const data={project:'ToolRent Pro',selected:tools.filter(t=>state.selected.includes(t.id)),days:state.days,delivery:state.delivery,clientType:$('#clientSelect').selectedOptions[0].textContent,createdAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='toolrent-order.json';a.click();URL.revokeObjectURL(a.href)});$('#reserveBtn').addEventListener('click',()=>{$('#bookingStatus').textContent=state.selected.length?'Демо-бронь создана. Можно экспортировать JSON заказа.':'Сначала выберите хотя бы один инструмент.'});const today=new Date().toISOString().slice(0,10);$('#dateInput').value=today;$('#dateInput').min=today;const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(el=>io.observe(el));renderCatalog()}
document.addEventListener('DOMContentLoaded',init);
